### ISSUE TITLE
text rendering: accept empty lines ?

### ISSUE THREAD

**Issue by jeanparpaillon** [CESNET/pOCCI#2]
When using pOCCI against erocci with text/plain rendering, tests fail because of empty lines in the body.
I suppose empty should be simply ignored

**Comment by jeanparpaillon** [comment]
Fixed in https://github.com/jeanparpaillon/pOCCI/commit/afc7522d0ee16b9ccd003cf7c50ac396e6a56892

**Comment by valtri** [comment]
Merged with #1. Thanks!
