### ISSUE TITLE
Test OCCI/CORE/CREATE/006: mixin creation syntax ?

### ISSUE THREAD

**Issue by jeanparpaillon** [CESNET/pOCCI#4]
The syntax of the request in test OCCI/CORE/CREATE/006 seems inappropriate.

Category: stufik; scheme="http://example.com/occi/my_stuff#"; class="mixin"; location: "/mixin/resource_tpl/extra_large/", rel: "http://schemas.ogf.org/occi/infrastructure#resource_tpl"

Shouldn't it be :
Category: stufik; scheme="http://example.com/occi/my_stuff#"; class="mixin"; location="/mixin/resource_tpl/extra_large/", rel="http://schemas.ogf.org/occi/infrastructure#resource_tpl"

**Comment by valtri** [comment]
Yes, the syntax is invalid. Fixed, thanks!

This test is not called by default and may have other problems.
