### ISSUE TITLE
OCCI/CORE/READ/002 : what's expected ?

### ISSUE THREAD

**Issue by jeanparpaillon** [CESNET/pOCCI#6]
Hi, I can't figure out what's expected in this test. Regarding the code in https://github.com/CESNET/pOCCI/blob/master/pOCCI/CORE.py#L471, it seems like the test is looking for a mixin related to resource_tpl ?
In this case, specification is not clear about if mixins related to resource_tpl are mandatory or not.

**Comment by valtri** [comment]
This test tries to get entities belonging to some (any) OCCI Kind or Mixin. So we need any "reasonable" Kind/Mixin to start with.

I guess theoretically resource_tpl is not mandatory in OCCI, practically it is required in EGI FedCloud. Maybe CORE/READ/002 could be somehow improved and be more dynamic (for example trying both: resource_tpl and os_tpl and consider success with any of that mixin?)

**Comment by jeanparpaillon** [comment]
Ok. What I don't understand is the line https://github.com/CESNET/pOCCI/blob/master/pOCCI/CORE.py#L476
From what I understand, you're looking for a mixin which is related to itself. Am I wrong ?

Or, the OCCI text rendering is not clear about what to display in 'rel': parent ? depends ? applies ? all ?

**Comment by arax** [comment]
@jeanparpaillon 
The rendering is not clear on this ... we usually render parent (depends) first and the rest belongs to applies. That's the best we can do. As we all know, we need to get rid of the text rendering :)

**Comment by jeanparpaillon** [comment]
Ok, thanks for the clarification. I am updating erocci wrt it.
